import React, { useState } from 'react';
import { 
  X, 
  Sparkles, 
  Code, 
  BookOpen, 
  HelpCircle, 
  Microscope, 
  Send, 
  Bot, 
  User, 
  RotateCcw, 
  CheckCircle2,
  ExternalLink,
  Terminal
} from 'lucide-react';

interface NikAiModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface Message {
  role: 'user' | 'assistant';
  content: string;
  code?: string;
  codeLang?: string;
  quiz?: {
    question: string;
    options: string[];
    correctIndex: number;
    explanation: string;
  };
}

export const NikAiModal: React.FC<NikAiModalProps> = ({ isOpen, onClose }) => {
  const [currentMode, setCurrentMode] = useState<'study' | 'coding' | 'quiz' | 'research'>('coding');
  const [inputText, setInputText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [quizSelectedOption, setQuizSelectedOption] = useState<number | null>(null);

  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      content: "Hello! I'm **NikAI**, an intelligent full-stack assistant developed by **Naitik Pandey** using FastAPI, React, and Google Gemini API. Select a workspace mode below or type a query to test my capabilities!",
      codeLang: 'python',
      code: `# NikAI Initialized
from fastapi import FastAPI
app = FastAPI(title="NikAI Service")

# Ready to assist in Coding, Study, Research & Quiz modes!`
    }
  ]);

  if (!isOpen) return null;

  const modePresets = [
    { id: 'coding', name: 'Coding Mode', icon: Code, badge: 'Python / Java / Web' },
    { id: 'study', name: 'Study Mode', icon: BookOpen, badge: 'Concepts & AI/ML' },
    { id: 'quiz', name: 'Quiz Generator', icon: HelpCircle, badge: 'Interactive Tests' },
    { id: 'research', name: 'Research Mode', icon: Microscope, badge: 'Deep Syntheses' },
  ] as const;

  const quickPrompts = {
    coding: [
      "Write a FastAPI endpoint with Pydantic request validation",
      "Implement Binary Search Tree in Java with insertion logic",
      "Explain React useEffect dependency array best practices"
    ],
    study: [
      "Explain Gradient Descent and Learning Rate simply",
      "How does Backpropagation calculate neural network gradients?",
      "What is the difference between Supervised and Unsupervised learning?"
    ],
    quiz: [
      "Generate a quiz question on Python Object-Oriented Programming",
      "Generate a quiz question on Machine Learning Overfitting vs Underfitting"
    ],
    research: [
      "Summarize Transformer Self-Attention vs Recurrent Neural Networks",
      "Explain the architectural difference between REST and GraphQL"
    ]
  };

  const handleSendPrompt = (promptText: string) => {
    if (!promptText.trim()) return;

    const userMessage: Message = {
      role: 'user',
      content: promptText
    };

    setMessages(prev => [...prev, userMessage]);
    setInputText('');
    setIsTyping(true);
    setQuizSelectedOption(null);

    // Simulate AI response based on mode and query
    setTimeout(() => {
      let assistantResponse: Message;

      if (currentMode === 'quiz' || promptText.toLowerCase().includes('quiz')) {
        assistantResponse = {
          role: 'assistant',
          content: "Here is an interactive concept check generated by NikAI:",
          quiz: {
            question: "Which technique is commonly used to prevent overfitting in deep neural networks?",
            options: [
              "Increasing the learning rate to 10.0",
              "Dropout regularization & Early Stopping",
              "Removing all validation datasets",
              "Using only linear activation functions"
            ],
            correctIndex: 1,
            explanation: "Dropout randomly deactivates a fraction of neurons during training, preventing co-adaptation of features. Early stopping halts training when validation loss stops improving."
          }
        };
      } else if (currentMode === 'coding' || promptText.toLowerCase().includes('fastapi') || promptText.toLowerCase().includes('java')) {
        assistantResponse = {
          role: 'assistant',
          content: `Here is the clean, production-ready implementation generated for **${promptText}**:`,
          codeLang: promptText.toLowerCase().includes('java') ? 'java' : 'python',
          code: promptText.toLowerCase().includes('java') 
            ? `// Binary Search Tree Node in Java
public class BSTNode {
    int val;
    BSTNode left, right;

    public BSTNode(int item) {
        val = item;
        left = right = null;
    }

    public static BSTNode insert(BSTNode root, int key) {
        if (root == null) return new BSTNode(key);
        if (key < root.val) root.left = insert(root.left, key);
        else if (key > root.val) root.right = insert(root.right, key);
        return root;
    }
}`
            : `# FastAPI RESTful Endpoint with Pydantic Model
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field
from typing import Optional

app = FastAPI()

class TaskItem(BaseModel):
    title: str = Field(..., min_length=3, max_length=100)
    completed: bool = False
    priority: int = Field(default=1, ge=1, le=5)

@app.post("/api/tasks", status_code=status.HTTP_201_CREATED)
async def create_task(task: TaskItem):
    # Simulated database insertion in SQLite
    return {"status": "created", "data": task.dict()}`
        };
      } else {
        assistantResponse = {
          role: 'assistant',
          content: `### Concept Breakdown: ${promptText}\n\n1. **Core Intuition**: In machine learning, algorithms learn statistical weights by optimizing an objective loss function. \n2. **Mathematical Foundation**: Using calculus gradients ($\\nabla L(\\theta)$), the model iteratively steps toward the global minimum.\n3. **Practical Application**: Implemented in frameworks like PyTorch or Scikit-Learn to train classification models with high generalization accuracy.`,
        };
      }

      setMessages(prev => [...prev, assistantResponse]);
      setIsTyping(false);
    }, 700);
  };

  const handleReset = () => {
    setMessages([
      {
        role: 'assistant',
        content: "Workspace refreshed. What would you like to explore or solve today?",
        codeLang: 'python',
        code: `# NikAI Session Cleared\n# Ready for next prompt in ${currentMode.toUpperCase()} mode.`
      }
    ]);
    setQuizSelectedOption(null);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      
      {/* Modal Container */}
      <div className="relative w-full max-w-4xl h-[85vh] max-h-[780px] bg-[#0B1020] border border-cyan-500/40 rounded-2xl shadow-2xl flex flex-col overflow-hidden text-slate-200">
        
        {/* Modal Header */}
        <div className="px-5 py-3.5 bg-[#070B14] border-b border-white/10 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center text-white">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="font-heading font-bold text-white text-base">NikAI Simulator</span>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-cyan-950/60 border border-cyan-500/30 text-cyan-300">
                  FastAPI • Gemini 2.0 Flash • SQLite
                </span>
              </div>
              <p className="text-[11px] text-slate-400 font-mono">Interactive project sandbox by Naitik Pandey</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleReset}
              className="p-1.5 rounded-lg bg-slate-800 text-slate-300 hover:text-white hover:bg-slate-700 transition-colors text-xs flex items-center gap-1 font-mono"
              title="Reset conversation"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Reset</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg bg-slate-800 text-slate-300 hover:text-white hover:bg-red-950/50 hover:border-red-500/40 transition-colors"
              aria-label="Close modal"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Workspace Mode Tabs */}
        <div className="px-4 py-2 bg-[#111827] border-b border-white/5 flex items-center gap-2 overflow-x-auto">
          {modePresets.map(mode => {
            const Icon = mode.icon;
            const isActive = currentMode === mode.id;
            return (
              <button
                key={mode.id}
                onClick={() => {
                  setCurrentMode(mode.id);
                  setQuizSelectedOption(null);
                }}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all flex items-center gap-1.5 ${
                  isActive
                    ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-sm'
                    : 'text-slate-400 hover:text-white hover:bg-white/5'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{mode.name}</span>
                <span className="text-[10px] text-slate-400 hidden sm:inline">({mode.badge})</span>
              </button>
            );
          })}
        </div>

        {/* Chat Feed */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-4 bg-[#070B14]/80">
          {messages.map((msg, idx) => (
            <div
              key={idx}
              className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              {msg.role === 'assistant' && (
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-600 to-cyan-600 flex items-center justify-center shrink-0 text-white shadow-md">
                  <Bot className="w-4 h-4" />
                </div>
              )}

              <div className={`max-w-[85%] sm:max-w-[75%] rounded-2xl p-4 text-xs sm:text-sm leading-relaxed ${
                msg.role === 'user'
                  ? 'bg-blue-600 text-white shadow-md rounded-tr-none'
                  : 'bg-[#111827] border border-white/10 text-slate-200 rounded-tl-none shadow-lg'
              }`}>
                <div className="whitespace-pre-wrap">{msg.content}</div>

                {/* Code Block if any */}
                {msg.code && (
                  <div className="mt-3 rounded-xl bg-[#070B14] border border-white/10 overflow-hidden font-mono text-xs">
                    <div className="px-3 py-1.5 bg-slate-900 border-b border-white/5 flex items-center justify-between text-[11px] text-slate-400">
                      <span className="flex items-center gap-1">
                        <Terminal className="w-3 h-3 text-cyan-400" />
                        <span>{msg.codeLang || 'code'}</span>
                      </span>
                    </div>
                    <pre className="p-3 overflow-x-auto text-cyan-200">
                      <code>{msg.code}</code>
                    </pre>
                  </div>
                )}

                {/* Interactive Quiz if any */}
                {msg.quiz && (
                  <div className="mt-3 p-3.5 rounded-xl bg-[#070B14] border border-cyan-500/30 space-y-2.5">
                    <div className="font-semibold text-white text-xs sm:text-sm font-sans flex items-start gap-1.5">
                      <HelpCircle className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                      <span>{msg.quiz.question}</span>
                    </div>

                    <div className="space-y-1.5 pt-1">
                      {msg.quiz.options.map((opt, oIdx) => {
                        const isSelected = quizSelectedOption === oIdx;
                        const isCorrect = oIdx === msg.quiz!.correctIndex;
                        let btnStyle = "bg-slate-800/80 border-slate-700 text-slate-300 hover:border-cyan-400";
                        if (quizSelectedOption !== null) {
                          if (isCorrect) {
                            btnStyle = "bg-emerald-950/80 border-emerald-500 text-emerald-200 font-semibold";
                          } else if (isSelected) {
                            btnStyle = "bg-red-950/80 border-red-500 text-red-200";
                          }
                        }

                        return (
                          <button
                            key={oIdx}
                            onClick={() => setQuizSelectedOption(oIdx)}
                            className={`w-full text-left p-2.5 rounded-lg text-xs border transition-all flex items-center justify-between ${btnStyle}`}
                          >
                            <span>{String.fromCharCode(65 + oIdx)}. {opt}</span>
                            {quizSelectedOption !== null && isCorrect && (
                              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                            )}
                          </button>
                        );
                      })}
                    </div>

                    {quizSelectedOption !== null && (
                      <div className="p-2.5 rounded-lg bg-slate-900 border border-white/10 text-xs text-slate-300 mt-2">
                        <span className="font-semibold text-cyan-300">Explanation: </span>
                        {msg.quiz.explanation}
                      </div>
                    )}
                  </div>
                )}
              </div>

              {msg.role === 'user' && (
                <div className="w-8 h-8 rounded-lg bg-slate-800 flex items-center justify-center shrink-0 text-slate-300">
                  <User className="w-4 h-4" />
                </div>
              )}
            </div>
          ))}

          {isTyping && (
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-600 to-cyan-600 flex items-center justify-center text-white">
                <Bot className="w-4 h-4" />
              </div>
              <div className="p-3 rounded-2xl bg-[#111827] border border-white/10 text-slate-400 text-xs flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-cyan-400 animate-bounce"></span>
                <span className="w-2 h-2 rounded-full bg-cyan-400 animate-bounce [animation-delay:0.2s]"></span>
                <span className="w-2 h-2 rounded-full bg-cyan-400 animate-bounce [animation-delay:0.4s]"></span>
                <span className="font-mono text-[11px]">NikAI is generating response...</span>
              </div>
            </div>
          )}
        </div>

        {/* Quick Prompts Bar */}
        <div className="px-4 py-2 bg-[#0B1020] border-t border-white/5 flex items-center gap-2 overflow-x-auto">
          <span className="text-[10px] font-mono text-slate-400 shrink-0">Sample Prompts:</span>
          {quickPrompts[currentMode].map((prompt, pIdx) => (
            <button
              key={pIdx}
              onClick={() => handleSendPrompt(prompt)}
              className="px-2.5 py-1 rounded-md text-[11px] font-mono bg-[#111827] border border-white/10 hover:border-cyan-500/40 hover:text-cyan-300 text-slate-300 whitespace-nowrap transition-colors"
            >
              {prompt}
            </button>
          ))}
        </div>

        {/* Input Bar */}
        <div className="p-3.5 bg-[#070B14] border-t border-white/10 flex items-center gap-2">
          <input
            type="text"
            placeholder={`Ask NikAI in ${currentMode} mode...`}
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSendPrompt(inputText);
              }
            }}
            className="flex-1 px-4 py-2.5 rounded-xl bg-[#111827] border border-white/10 text-xs sm:text-sm text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400 transition-all font-sans"
          />
          <button
            onClick={() => handleSendPrompt(inputText)}
            disabled={!inputText.trim() || isTyping}
            className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white font-medium text-xs sm:text-sm flex items-center gap-1.5 shadow-md shadow-blue-600/20 disabled:opacity-40 transition-all"
          >
            <Send className="w-4 h-4" />
            <span className="hidden sm:inline">Send</span>
          </button>
        </div>

      </div>
    </div>
  );
};
